# Generated by Django 4.1.3 on 2022-11-16 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_spot_x_spot_y'),
        ('users', '0002_customuser_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='spots.spot'),
        ),
    ]
