# Generated by Django 4.1.3 on 2022-11-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='x',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='y',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
