version: '3.8'

services:

  nginx:
    image: nginx:1.22.1
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../static:/var/html/static/
      - ../media/:/var/html/media/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf